spring.application.name=employee

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://root:XxdvxpPcumnpWeCcKFdzEsxLnMcpwXDC@yamanote.proxy.rlwy.net:14280/railway}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:XxdvxpPcumnpWeCcKFdzEsxLnMcpwXDC}

spring.jpa.hibernate.ddl-auto=update

cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}